version: '3'

services:
  spring-boot-docker-app:
    image: dmitry-spring-boot-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8181
    volumes:
      - /storage/my-app