{
 "title": "Monitoring-bokhanych",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Count running containers",
   "type": "stat",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana http://localhost:3000",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"http://192.168.100.222:3000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blackbox http://localhost:9115",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"http://192.168.100.222:9115\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus http://localhost:9090",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"http://192.168.100.222:9090\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spring-boot http://localhost:8080/helloworld/hello",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"http://192.168.100.222:8080/helloworld/hello\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "History of count running containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"running\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}